name: Update "Last updated" in README (IST)

on:
  schedule:
    # Runs daily at 00:00 UTC (05:30 IST)
    - cron: "0 0 * * *"
  workflow_dispatch: {}  # allow manual run

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update timestamp in README
        shell: bash
        run: |
          set -euo pipefail

          TZ="Asia/Kolkata"
          export TZ
          NOW="$(date '+%Y-%m-%d %H:%M:%S %Z')"

          FILE="README.md"

          if [[ ! -f "$FILE" ]]; then
            echo "README.md not found at repo root"; exit 1
          fi

          awk -v ts="$NOW" '
            /<!--updated_at-->/ {
              print;
              getline; print "📅 Updated: " ts;
              getline; print;
              next
            }
            { print }
          ' "$FILE" > README.tmp && mv README.tmp "$FILE"

          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$FILE"
          git commit -m "chore: update README last updated timestamp (IST: $NOW)"
          git push
